version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  twelvefactor.webapi:
    build:
      context: .
      dockerfile: TwelveFactor.WebApi/Dockerfile
    container_name: twelvefactor
    restart: always
    ports:
      - "5000:80" # <- change port 5000 if necessary!
    environment:
      - TF_DbConnectionString=mongodb://mongodb:27017
      - TF_DbNAme=PersonDb
    depends_on:
      - mongodb